CREATE DATABASE BreadmanDB;

use BreadmanDB;

CREATE TABLE Customer (
idCustomerID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
vFirstName VARCHAR(32) NOT NULL,
vLastName VARCHAR(32) NOT NULL,
vDeliveryAddress VARCHAR(64) NOT NULL,
vType VARCHAR(16) NOT NULL,
vContactNumber VARCHAR(16) NOT NULL
);
CREATE TABLE Orders (
idOrderID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
idCustomerID INT NOT NULL REFERENCES Customer(idCustomerID),
vOrderStatus VARCHAR(8) NOT NULL DEFAULT 'Pending',
dOrderDate DATE NOT NULL,
vOrderType VARCHAR(8) NOT NULL,
vOrderDesc VARCHAR(128) NULL,
vRequestImage VARCHAR(128) NULL,
vReferenceNo VARCHAR (16) NOT NULL
);
CREATE TABLE Supplies (
idItemID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
vItemName VARCHAR(32) NOT NULL,
vItemDesc VARCHAR(128) NULL,
dcItemInKilos DECIMAL NULL,
dcItemInLiters DECIMAL NULL,
idSupplierID INT NOT NULL REFERENCES Suppliers(idSupplierID)
);
CREATE TABLE OrderItems (
idOrderItemsID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
idGoodsID INT NOT NULL REFERENCES Goods(idGoodsID),
idOrderID INT NOT NULL REFERENCES Orders(idOrderID),
iQuantity INT NULL
);
CREATE TABLE Goods (
idGoodsID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
vGoodsName VARCHAR(32) NOT NULL,
vGoodsDesc VARCHAR(128) NULL,
iQuantity INT NULL,
dcPrice DECIMAL(15,2) NOT NULL
);
CREATE TABLE Suppliers (
idSupplierID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
vSupplierName VARCHAR(32) NOT NULL,
vContactNumber VARCHAR(16) NULL,
dSupplierJoined DATE NULL,
vSupplierDesc VARCHAR(128) NULL,
vSupplierAddress VARCHAR(64) NULL
);
CREATE TABLE Sales (
idSalesID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
idOrderID INT NOT NULL REFERENCES Orders(idOrderID),
idCustomerID INT NOT NULL REFERENCES Customer(idCustomerID),
vSalesDesc VARCHAR(64) NULL,
dSaleDate DATE NOT NULL,
dcPrice DECIMAL(15,2) NOT NULL,
dcAppliedTax DECIMAL NOT NULL,
dcTotalPrice DECIMAL(15,2) NOT NULL
);
CREATE TABLE Products (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
idGoodsID NOT NULL REFERENCE Goods(idGoodsID),
vName VARCHAR(32) NOT NULL,
vDescription VARCHAR(128) NULL,
dcPrice DECIMAL NULL,
vProductImage VARCHAR(64) NULL
);
CREATE TABLE MasterUser (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
vUserName VARCHAR(32) NOT NULL,
vPassword VARCHAR(50) NOT NULL,
vName VARCHAR(16) NOT NULL,
vAdminType VARCHAR(16) NOT NULL DEFAULT 'admin'
);
